"use client";

import {useState} from "react";
type Q={id:string;category:string;skill:string;difficulty:string;question:string;rationale:string;source:string};
type P={target_role:string;years_experience:number;skills:string[];claims:string[];projects:string[];required_skills:string[]};
type E={score:number;strengths:string[];weaknesses:string[];follow_up_question?:string};
const API=process.env.NEXT_PUBLIC_API_URL||"http://localhost:8000";

export default function Home(){
 const[resume,setResume]=useState(""),[jd,setJd]=useState(""),[role,setRole]=useState("Data Analyst"),[years,setYears]=useState("5"),[mode,setMode]=useState("mixed");
 const[plan,setPlan]=useState<{profile:P;questions:Q[]}|null>(null),[index,setIndex]=useState(0),[answer,setAnswer]=useState(""),[feedback,setFeedback]=useState<E|null>(null),[asked,setAsked]=useState<Q[]>([]),[evals,setEvals]=useState<E[]>([]),[report,setReport]=useState<any>(null),[loading,setLoading]=useState(false);
 async function start(){setLoading(true);const r=await fetch(API+"/v1/interview/plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({resume_text:resume,job_description:jd,target_role:role,years_experience:Number(years),mode,question_count:10})});setPlan(await r.json());setAsked([]);setEvals([]);setReport(null);setIndex(0);setFeedback(null);setAnswer("");setLoading(false)}
 async function submit(){if(!plan)return;setLoading(true);const r=await fetch(API+"/v1/interview/evaluate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:plan.questions[index],answer,candidate:plan.profile})});setFeedback(await r.json());setLoading(false)}
 async function next(){if(!plan||!feedback)return;setLoading(true);const q=plan.questions[index],a=[...asked,q],e=[...evals,feedback];const r=await fetch(API+"/v1/interview/next",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({candidate:plan.profile,available_questions:plan.questions,asked_questions:a,evaluations:e,last_question:q,last_evaluation:feedback})});const out=await r.json();setAsked(a);setEvals(e);setFeedback(null);setAnswer("");if(out.interview_complete)setReport(out.readiness);else setIndex(plan.questions.findIndex(x=>x.id===out.question.id));setLoading(false)}
 if(report)return <main className="shell"><header><div className="logo">CareerCoach <span>AI</span></div></header><section className="card"><div className="eyebrow">INTERVIEW READINESS</div><div className="score">{report.overall_readiness}<small>/100</small></div><h1>{report.recommendation}</h1><div className="grid">{Object.entries(report.skill_scores||{}).map(([k,v])=><div className="metric" key={k}><b>{k}</b><strong>{String(v)}</strong></div>)}</div><h3>Priority gaps</h3><p>{(report.priority_gaps||[]).join(" · ")||"No major gaps detected."}</p><button onClick={()=>setPlan(null)}>Start another interview</button></section></main>;
 if(plan){const q=plan.questions[index];return <main className="shell"><header><div className="logo">CareerCoach <span>AI</span></div><div className="pill">Adaptive interview</div></header><section className="card"><div className="eyebrow">{q.category.toUpperCase()} · {q.skill} · {q.difficulty}</div><h1>{q.question}</h1><textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Answer as if you are in the real interview..."/>{!feedback?<button disabled={loading||!answer.trim()} onClick={submit}>{loading?"Evaluating…":"Submit answer"}</button>:<div className="feedback"><div className="score">{feedback.score}<small>/100</small></div><b>Strengths</b>{feedback.strengths.map(x=><p key={x}>✓ {x}</p>)}<b>Improve</b>{feedback.weaknesses.map(x=><p key={x}>→ {x}</p>)}{feedback.follow_up_question&&<div className="follow"><b>AI follow-up</b><p>{feedback.follow_up_question}</p></div>}<button disabled={loading} onClick={next}>{loading?"Adapting…":"Continue adaptive interview"}</button></div>}</section></main>}
 return <main className="shell"><header><div className="logo">CareerCoach <span>AI</span></div><div className="tag">Adaptive interview intelligence</div></header><section className="hero"><div className="eyebrow">RESUME-PROOF · ADAPTIVE · ROLE-SPECIFIC</div><h1>Practice the interview you’re actually going to face.</h1><p>CareerCoach probes weak areas instead of blindly moving through a fixed question list.</p></section><section className="card form"><label>Target role<input value={role} onChange={e=>setRole(e.target.value)}/></label><label>Years of experience<input value={years} onChange={e=>setYears(e.target.value)}/></label><label>Interview mode<select value={mode} onChange={e=>setMode(e.target.value)}><option value="mixed">Mixed</option><option value="technical">Technical</option><option value="behavioral">Behavioral</option><option value="pressure">Pressure</option></select></label><label>Resume<textarea value={resume} onChange={e=>setResume(e.target.value)} placeholder="Paste your resume text here…"/></label><label>Job description<textarea value={jd} onChange={e=>setJd(e.target.value)} placeholder="Paste the job description here…"/></label><button disabled={loading||!role} onClick={start}>{loading?"Building interview…":"Start AI interview"}</button></section></main>
}